### ISSUE TITLE
Di tabel pengguna, hapus field `password_murni`

### ISSUE THREAD

**Issue by ceefour** [lskk/tadj#3]
Ini security hole yang major. :(

**Comment by ilhamfadllah** [comment]
Sebenarnya saya lagi ada kendala untuk fitur reset password, thus di simpan terlebih dahulu ke tabel. ASAP would be proper mechanism as we expected. Thanks for your attention.

**Comment by ceefour** [comment]
Kendalanya apa mas? Siapa tau bs kasih masukan

**Comment by ilhamfadllah** [comment]
Singkatnya tidak bisa mengirim email, dengan masalah detail yang sama seperti disini:
http://stackoverflow.com/questions/37411236/curl-error-35-unknown-ssl-protocol-error-in-connection-to-api-mailgun?s=1|1.8700 .

Sudah dicoba dgn cara menambahkan sertifikat SSL, belum berhasil.

**Comment by ceefour** [comment]
Karena servernya di network ITB, tebakanku adalah proxy authentication belum disetting (untuk Laravel ya?). Coba konfirmasi dengan pak Pras bagaimana setting proxy outgoing HTTP(S) untuk server TADJ?

**Comment by ceefour** [comment]
Tapi itu beda issue sih, column ini tetap harus dihapus. (Tanpa password murni pun, admin tetap dapat mereset password pengguna secara manual)

Untuk masalah tidak bisa kirim email, baiknya bikin issue terpisah.

**Comment by ilhamfadllah** [comment]
Kirim email tujuannya untuk reset password.

Setuju, akan hapus setelah fitur reset password setelah sudah jadi fitur reset password dari admin.

**Comment by ceefour** [comment]
Sip sip .. semoga email-nya segera bisa ya (y)

**Comment by ilhamfadllah** [comment]
Udah dihapus field 'password_murni' nya
